### ISSUE TITLE
Add auto-permission approval mechanism for every sensor state function

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [mutualmobile/ComposeSensors#68]
The idea is to explore if it is possible to ask for permissions whenever the user starts consuming any sensor state.

If implemented successfully, the developers won't need to write code for asking permissions for the sensors they are using, the library will do it for them 🎉 

**For example**: Whenever a user starts consuming values from `rememberHeartRateSensorState`, the required permission i.e. `android.permission.BODY_SENSORS` should automatically be requested first and only when the user grants it, the state function should start emitting sensor values.

## **TODO**
- [ ] Research which sensor requires what permission
- [ ] Search which permission is required for High Speed / Real-Time sensor data emission
- [ ] Make sure to emit default value (`0` for Float and `false` for Boolean) while the permission is being requested
- [ ] Expose the permission state (granted / denied) from the sensor state classes

## **Resources**
1. https://developer.android.com/training/wearables/versions/4/background-body-sensors

**Comment by Chandra-Mauli-Sharma** [comment]
I would like to work on it.

**Comment by shubhamsinghmutualmobile** [comment]
Sure, please feel free to raise a PR @Chandra-Mauli-Sharma 🌟 You don't need to be assigned to the ticket in order to work on it 👍 

If the PR is in a working state, we'll assign this issue to you and merge it ✅

**Comment by Chandra-Mauli-Sharma** [comment]
Ok, will start working on it.
